services:
  - type: web
    name: reva-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python reva_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
